source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, "9.0"

#inhibit_all_warnings!
use_frameworks!

target 'FLLogs-Example' do
    pod 'FLLogs', :path => '../'
end
